name: "Chromatic"
on: push
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 50

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Explicitly use Node.js 20
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build Storybook in the design-system app
        run: |
          cd apps/design-system  # Change to the design-system directory
          yarn build-storybook   # Run the build command for Storybook

      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: apps/design-system  # Set the correct directory
          buildScriptName: build-storybook  # Name of your build script
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: ${{ github.ref == 'refs/heads/main' }}
          exitOnceUploaded: true
          skip: "dependabot/**"
