name: "Chromatic"
on: push
jobs:
  chromatic-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 50
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Explicitly use Node.js 20
          cache: "yarn"  # Use Yarn cache instead of npm cache
      - name: Install dependencies
        run: yarn install --frozen-lockfile  # Use Yarn instead of npm ci
      - name: Build Storybook dependencies
        run: yarn build -- --filter="design-system^..."  # Use Yarn to build Storybook
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          workingDir: apps/design-system
          buildScriptName: build
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          autoAcceptChanges: ${{ github.ref == 'refs/heads/main' }}
          exitOnceUploaded: true
          skip: "dependabot/**"
